### PR TITLE
Added Portuguese (Brazil) language

### PR DESCRIPTION
**Pull request by WendellAdriel**
Initial commit for opening the Portuguese translation. I am not aware of any peers who are willing to contribute right now.

I write some posts in English and in Portuguese and already translated some articles:

- https://github.com/CodeShareEducation/old-articles/blob/master/2016-03-14-duelo-dos-pre-processadores.md

- https://github.com/CodeShareEducation/old-articles/blob/master/2016-03-29-entendendo-o-async-e-o-await-em-javascript.md

- https://github.com/CodeShareEducation/old-articles/blob/master/2016-03-30-como-escalonar-o-laravel-horizontalmente-com-docker.md

These are some examples of posts I already translated. I'm willing to help in the translations to help the developers in Brazil because we still have a lot of devs that don't have good skills with the English language.

### CODE REVIEW

**Comment by WendellAdriel** [comment]
Sorry @tesseralis, I didn't see that before.
I'll update my commit with their usernames

**Comment by tesseralis** [comment]
Thanks! Let's wait until at least one of them responds to make sure :)

**Comment by cezaraugusto** [comment]
thanks @WendellAdriel for the initiative. I know @gmsecrieru https://github.com/reactjs/reactjs.org/issues/1605#issuecomment-458936960 is also interested.

**Comment by tibuurcio** [comment]
Hi Wendell, I would like to help with translations for brazilian portuguese, could you please add me as a contributor?

I have some experience writing [tutorials](https://github.com/iptp/minesweeper/wiki/The-Minesweeper-game) in [english](https://github.com/iptp/Japanese-Typing-Game/wiki). Please note that those writings are from 2016 so my english is a bit better by now.

Thank you 😄

**Comment by WendellAdriel** [comment]
Hi @cezaraugusto and @tibuurcio.
Already added @gmsecrieru and you (@tibuurcio) on the PR!!!

**Comment by glaucia86** [comment]
LGTM. Thanks all!

**Comment by tesseralis** [comment]
Creating a repository for you! It should be read in a few minutes and you should receive an invite on github.

**Comment by jcserracampos** [comment]
Thank you for inviting me!

**Comment by glaucia86** [comment]
Thanks a lot @tesseralis for inviting me!

**Comment by lffg** [comment]
Hi, @tesseralis! I'm also interested in contributing to this. :)

**Comment by fjoshuajr** [comment]
@lffg glad you're interested in contributing. Pick a page here: https://github.com/reactjs/pt-BR.reactjs.org/issues/1

**Pull request merged**
