### PR TITLE
Add tagalog/filipino language support

### PR DESCRIPTION
**Pull request by elrimando**
I have no real experience with docs translation other than working with other people both speaking and writing in Filipino and English.

Hoping that my _"kababayans"_ (fellow Filipino) out there notice this and join me translating the react docs into the language that we all love!

### CODE REVIEW

**Comment by tesseralis** [comment]
Thanks for volunteering! I'll keep this up to see if anyone else wants to join :)

**Comment by lacson17** [comment]
Hello @elrimando and @tesseralis,

I'd like to help create/maintain translations for Tagalog. I'm fluent in the language, so I'd be more than happy to contribute!

In terms of translation experience, I've done English-French translation work as a developer for the Bank of Montreal's internal Angular and React Native projects.

**Comment by tesseralis** [comment]
@lacson17 sounds good! @elrimando, let me know if you're still up for this and I'll make you your repo.

**Comment by elrimando** [comment]
Sweet! Hello @lacson17 

@tesseralis I'm still up and ready!

**Comment by tesseralis** [comment]
@elrimando, @lacson17, your new repo is here: https://github.com/reactjs/tl.reactjs.org/issues/1

Happy translating!

**Pull request merged**
