### PR TITLE
Add Korean maintainers

### PR DESCRIPTION
**Pull request by simsim0709**
This is PR for translations in Korean.

A little bit of my translation and open source projects:

translation
https://www.vobour.com/series/it-%EB%B8%94%EB%A1%9C%EA%B7%B8-%EB%B2%88%EC%97%AD

open source
https://github.com/learn-vuejs/vue-patterns/

@tesseralis, I just sent messages to 2 people who speak Korean, and I'm waiting for a response. 
Could you add them later or merge this pr a little bit later?

Thanks.

### CODE REVIEW

**Comment by tesseralis** [comment]
I'll wait to merge the PR :)

**Comment by gnujoow** [comment]
@simsim0709 

I would like to contribute Korean translation ;) 

could you list my username @gnujoow on PR commit?

**Comment by tesseralis** [comment]
@gnujoow could you tell us a little bit about your experience with translating or open source?

**Comment by gnujoow** [comment]
@tesseralis 

I translated a page of https://github.com/aikorea/cs231n and made glossary for better translation. And translated few pages of [yarn](https://yarnpkg.com/lang/en/) on [crowdin](https://crowdin.com/project/yarn/ko#). 

for open source, I haven't contributed on code level but have fixed some open sources' document. recently I fixed gastbyjs tutorial.
https://github.com/gatsbyjs/gatsby/pull/10488

As someone who really likes React, I would appreciate enormously if i could maintain and translate React docs ;)

**Comment by b9words** [comment]
@simsim0709 @tesseralis 

Hi, I would also like to contribute to Korean translation. I have not participated in open source projects before, but am very experienced in language localization & en-ko translations. 

I headed the localization of Storefront (real-estate IT platform) in Korea, and am participating in multinational blockchain project (precium.io) as a core developer. My credentials can be viewed at https://www.linkedin.com/in/jinyong-kim/ for your reference :)

I really hope I can contribute to this awesome project!

**Comment by hg-pyun** [comment]
@simsim0709 
Thank you for email. I want to participate translations :D

**Comment by simsim0709** [comment]
Thanks all, @hg-pyun @gnujoow @b9words 

I'm not sure if I have in charge of adding maintainers on the list. I'd better wait for @tesseralis 's confirm, then I will change it.

**Comment by tesseralis** [comment]
@simsim0709  I've created a repo for you! You should have received an invite to join the react organization. Happy translating :)

**Comment by simsim0709** [comment]
@tesseralis some other people want to join the Korean translation repo.
Can I manage "collaborators & teams" of Korean translation repo?

Thanks.

**Comment by tesseralis** [comment]
You should be able to add them here: https://github.com/orgs/reactjs/teams/reactjs-org-korean-translation/members

And this will give them access to the repo!

**Comment by deminoth** [comment]
Can I participate?
- https://lunit.gitbook.io/redux-in-korean/ (maintainer)
- https://medium.com/@Dev_Bono/당신에게-redux는-필요-없을지도-모릅니다-b88dcd175754

**Comment by simsim0709** [comment]
Hi, @deminoth 

Korean translation repo is here https://github.com/reactjs/ko.reactjs.org/

Thanks 👍

**Pull request merged**
