### PR TITLE
Add Nepali language

### PR DESCRIPTION
**Pull request by samundrak**
Hi There,
I would love to contribute to translating to `Nepali` language.

Some of mine Open source contribution:
- https://github.com/babel/website/pull/1500
- https://github.com/GoogleChromeLabs/size-plugin/pull/13
- https://github.com/fusionjs/fusion-cli/pull/462

### CODE REVIEW

**Comment by tesseralis** [comment]
Hi @samundrak! Thanks for contributing. I'll keep this open to find more maintainers and spread the word!

**Comment by samundrak** [comment]
closing, as I didn't get any support

**Comment by tesseralis** [comment]
I'm going to reopen this! Don't lose hope! I think for some other languages it took around a week for more people to show up. I'll retweet it as well so be patient :)

**Comment by nootanghimire** [comment]
@tesseralis @samundrak  : I like this and would contribute in me free time!

**Comment by tesseralis** [comment]
Yay! @samundrak let me know and I can start you off!

**Comment by samundrak** [comment]
Thanks @tesseralis , i  updated maintainers

**Pull request merged**
