### PR TITLE
Feat: Add Georgian language support

### PR DESCRIPTION
**Pull request by GugaGongadze**
Hello, my workmates at [Vobi](https://github.com/vobi-io) and me would like to translate React docs to Georgian.
Vobi is a software development agency specializing in JS ecosystem. We don't have much translating experience but we love all things open-source and even run React training courses in Georgian language.

### CODE REVIEW

**Comment by RezikoChkadua** [comment]
approve \o/

**Comment by gtsitsvidze** [comment]
Approve !

**Comment by tesseralis** [comment]
Here you go! https://github.com/reactjs/ka.reactjs.org/issues/1

Please use this issue to keep track of your progress, and let me know if you need any help :)

**Comment by davidkadaria** [comment]
Hello, I want to contribute.

**Pull request merged**
