### PR TITLE
Added Macedonian language 🇲🇰

### PR DESCRIPTION
**Pull request by Aleksandandar-Nedelkovski**

### CODE REVIEW

**Comment by tesseralis** [comment]
Hi @Aleksandandar-Nedelkovski! Thanks for volunteering. We'll keep this issue open for others to find :)

**Comment by Aleksandandar-Nedelkovski** [comment]
Any update?

**Comment by Aleksandandar-Nedelkovski** [comment]
Hello @tesseralis! Any update here?

**Comment by gaearon** [comment]
Hi folks, sorry for no response.

We've been working on new React docs, and so translations of the old site were deprioritized.
In the meantime, it looks like our GitHub permissions sync may have broke.

Now that we've rolled out the new site and reset the repositories for new translations, I'm going to close all old pull requests including this one so that we can start from a clean slate. If you'd like to still make the same change, please open a new PR.

Thanks, and sorry for the churn.

**Pull request closed without merging**
