### PR TITLE
Add maintainer handle for Traditional Chinese

### PR DESCRIPTION
**Pull request by chloewlin**
This is my PR for translations in Traditional Chinese. I can add others who want to be maintainers later.

### CODE REVIEW

**Comment by tesseralis** [comment]
@chloewlin could you add the other maintainers who are interested in the same PR? I think @haimengzhang and @bugtender said in the other thread they were interested.

Could you briefly list your experience with translation or open source?

**Comment by chloewlin** [comment]
Hi @tesseralis of course! Sorry that I missed their responses. I just added @haimengzhang and @bugtender as maintainers. 

Quick question: I am reaching out to developers I know who might be interested in helping but are still waiting for their responses. Can I add maintainers later? 

About me: One of my most recent open source contribution is translating Dan's [blog](https://github.com/gaearon/overreacted.io). I also hold degrees in [English lit](https://www.linkedin.com/in/chloewlin/) and have worked on academic and technical translations for years as side projects.

**Comment by tesseralis** [comment]
Yeah! You can. I'll have to add them manually though :P

**Comment by tesseralis** [comment]
You can also probably just add them to the team once it's created; right now the maintainers list is only for generating the initial list of people (though it might end up being used to assign people to PRs for example)

**Comment by chloewlin** [comment]
Ah I see. Let me circle back in a bit. I want to invite 2-3 developers to join this project. I will let you know when the initial list is finalized. :)

**Comment by tesseralis** [comment]
@chloewlin yay! should I merge this PR now?

**Comment by chloewlin** [comment]
@tesseralis Yes, please do! :)

**Pull request merged**
