### PR TITLE
Serbian lang, add new maintainer

### PR DESCRIPTION
**Pull request by lxmarinkovic**
Hi @Milos5611 and @vaske , I would like to take part in sr lang translation

### CODE REVIEW

**Comment by vaske** [comment]
Great seems so we need some more hands-on 🚀

**Review by vaske — APPROVED** [review]

**Comment by lxmarinkovic** [comment]
@vaske  Thank you for such a quick response! It will be a pleasure to work on this with you 😃

**Comment by lxmarinkovic** [comment]
Hi @tesseralis  , it would be nice if you could do a review as I am keenly interested in joining the sr-lang team and starting contributing 🚀

**Comment by gaearon** [comment]
Hi folks, sorry for no response.

We've been working on new React docs, and so translations of the old site were deprioritized.
In the meantime, it looks like our GitHub permissions sync may have broke.

Now that we've rolled out the new site and reset the repositories for new translations, I'm going to close all old pull requests including this one so that we can start from a clean slate. If you'd like to still make the same change, please open a new PR.

Thanks, and sorry for the churn.

**Pull request closed without merging**
