### PR TITLE
Add Kannada

### PR DESCRIPTION
**Pull request by vageeesh**
Hello, I am from Karnataka India. I added  new language kannada here.

### CODE REVIEW

**Comment by tesseralis** [comment]
Hi @vageeesh! Thanks for volunteering. Could you talk a little bit about your translation or open-source software experience? Let's wait a bit and see if anyone else wants to contribute!

**Comment by anirudhbs** [comment]
I'd like to contribute to this as well. I am a native Kannada speaker, but this will be my first time contributing to such a big project.

**Comment by tesseralis** [comment]
@anirudhbs yay! @vageeesh, let me know if you're fine starting with just the two of you and I'll get your repo set up!

**Comment by anirudhbs** [comment]
Hey, yeah. That'd be really fun! What can I do to understand the workflow for the translation to be done right?

**Comment by sreekantho** [comment]
Hey, I could contribute too. Let me know when the repo has been set up.

**Comment by tesseralis** [comment]
@anirudhbs see here for the maintianer guide: https://github.com/reactjs/reactjs.org-translation/blob/master/maintainer-guide.md

@sreekantho could you talk a little bit about your background in the language or open source?

**Comment by sreekantho** [comment]
> @anirudhbs see here for the maintianer guide: https://github.com/reactjs/reactjs.org-translation/blob/master/maintainer-guide.md
> 
> @sreekantho could you talk a little bit about your background in the language or open source?

Native speaker of Kannada & also I have learnt Kannada as a language for over 12 years in School & College.
As far as open source experience is concerned. I have been managing projects written in ROR, bootstrap and so on. Please let me know if you need more info.

**Comment by tesseralis** [comment]
Here's your repo! https://github.com/reactjs/kn.reactjs.org

Please use this issue to track your progress: https://github.com/reactjs/kn.reactjs.org/issues/1

There should be more instructions on how to get started. Happy translating!

**Comment by vageeesh** [comment]
Hi , since i born in Karnataka i know Kannada language well . I did not worked in any open source project but i am very eager to contribute and see React documentation in my native language Kannada.

Thank you for creating the repo!

**Comment by anrao91** [comment]
@tesseralis Can I start contributing as well ? I am born and bought up in Karnataka and Kannada is my mother tongue. Also I am an active React developer.

**Comment by allthingsbeta** [comment]
@tesseralis -- Thanks for creating the Repo..
Kannada is my first language and i'm excited to contribute towards the same.
Pls add me as a maintainer so that i can get access to the resources and start my contributions.

Thanks and Happy Reacting !

**Pull request merged**
