### PR TITLE
Add Dutch language

### PR DESCRIPTION
**Pull request by Keraito**
Based on comments in https://github.com/reactjs/reactjs.org/issues/1605, @jochenboesmans, @rickbeerendonk, and I have shown interest in translating and maintaining a Dutch translation of the React docs.

Personally, I haven't had experience with translating to Dutch, but it's my native language, I'm working on [writing myself](https://medium.com/@keraito) and I've participated in some [Open Source work](https://github.com/storybooks/storybook/graphs/contributors). It sounds super fun to do something like maintaining a translation of the official docs 😃 !

Can the others double-check whether their github handles are correct in the language json file?

### CODE REVIEW

**Comment by jochenboesmans** [comment]
Hi!

Thanks for opening a PR. The commit seems correct to me.

Not much credentials on my end, but I'm happy to review my translations should there be any errors.

**Comment by tesseralis** [comment]
Done! Have fun translating!

Also, will you let me know how to say "yes" and "no"/"not yet" in Dutch so I can update the progress site? (isreacttranslatedyet.com)

**Comment by jochenboesmans** [comment]
@tesseralis Thanks!

Here are the translations:
"yes": "ja",
"no": "nee",
"not yet": "nog niet"

**Comment by tesseralis** [comment]
@Keraito @jochenboesmans @rickbeerendonk here's your repo! https://github.com/reactjs/nl.reactjs.org/issues/1

**Comment by Keraito** [comment]
Thank you very much @tesseralis 😊

**Comment by rickbeerendonk** [comment]
Thank you for adding me. I'm on very bad mobile connection in rural 🇨🇴 until Tuesday. Afterwards, expect me to be active.

**Pull request merged**
