### PR TITLE
added hindi language

### PR DESCRIPTION
**Pull request by saranshkataria**
I do not have any experience in translation before but would love to give this a shot! Since Hindi is the only other language I know of apart from English and there is no existing repo for it, created this PR. I have done some open source contributions recently and am one of the maintainers at gatsbyjs.

### CODE REVIEW

**Comment by tesseralis** [comment]
Thanks for volunteering! I think we'd like a more experienced translator on the team, but you can also be a maintainer! Feel free to post here: https://github.com/reactjs/reactjs.org/issues/1605 or on Twitter to see if you can find more maintainers!

**Comment by saranshkataria** [comment]
I know developers who might be willing to contribute, but don't know any experienced translators. Here's a tweet asking for more people: https://twitter.com/saranshk/status/1093721736208502789

**Comment by tesseralis** [comment]
@saranshkataria , @arshadkazmi42 is also interested in maintaining a hindi branch! If you two want to work together, just say so and I'll merge this repo :)

**Comment by arshadkazmi42** [comment]
@tesseralis I would love to work with @saranshkataria 
Below is my translation experience

#### Previous translation work
https://github.com/firstcontributions/first-contributions/blob/master/translations/README.hi.md

#### Reviewer for Hindi Language at [firstcontributions](firstcontributions)
https://github.com/firstcontributions/first-contributions/blob/master/.github/CONTRIBUTING.md#our-reviewers-sparkles

**Comment by tesseralis** [comment]
I updated the repo! Once @saranshkataria confirms, I can merge this in and start you off! ^_^

**Comment by arshadkazmi42** [comment]
Thank you 👍

**Comment by saranshkataria** [comment]
@tesseralis sure, happy to have any help :)
@arshadkazmi42 glad to virtually meet you. Let's kick this off!

**Comment by tesseralis** [comment]
https://github.com/reactjs/hi.reactjs.org/issues/1

@saranshkataria @arshadkazmi42 Here's your repo! Have fun translating! Let me know if you need any help :)

**Comment by arshadkazmi42** [comment]
@tesseralis Thanks alot for setting it up

**Comment by harshitjuneja** [comment]
Hey @tesseralis, @saranshkataria, and @arshadkazmi42. This looks exciting. I've been doing open source for a while and have made contributions for tux4kids in the past.

**Comment by tesseralis** [comment]
@harshitjuneja you can go to the issue and contribute! The other two can add you as a maintainer too if they want more help!

**Pull request merged**
