### PR TITLE
Add Persian language

### PR DESCRIPTION
**Pull request by sorousht**
Hey,

I would like to contribute to the Persian translation. I do not have much experience in translation, but I really enjoy writing some blog posts occasionally.
My previous works:
- [حرفه‌ای‌ها پیام کامیت گیت را چطور می نویسند؟](https://virgool.io/Software/%D8%AD%D8%B1%D9%81%D9%87-%D8%A7%DB%8C-%D9%87%D8%A7-%D9%BE%DB%8C%D8%A7%D9%85-%DA%A9%D8%A7%D9%85%DB%8C%D8%AA-%D8%B1%D8%A7-%DA%86%D8%B7%D9%88%D8%B1-%D9%85%DB%8C-%D9%86%D9%88%DB%8C%D8%B3%D9%86%D8%AF-ouopo27oknul)
- [Some old posts in dotnettips.info](https://www.dotnettips.info/writer/%d8%b3%d8%b1%d9%88%d8%b4%20%d8%aa%d8%b1%da%a9%20%d8%b2%d8%a7%d8%af%d9%87#/page/1/date/desc)

Please let me find other volunteers before accepting the PR.

### CODE REVIEW

**Comment by tesseralis** [comment]
@sJJdGG mentioned being interested here: https://github.com/reactjs/reactjs.org/issues/1605#issuecomment-460340883

**Comment by sorousht** [comment]
@sJJdGG May I add you the list of maintainers?

**Comment by zahrajoulaei** [comment]
I am glad to working voluntarily on this project, I have been also a volunteer mentor in the Nggirls community which tries to teach Angular to interested women in whole the world, and now I am also looking forward to having this amazing framework in Persian language with the aim of having better access for Persian language people.

**Comment by sorousht** [comment]
@zahrajoulaei Great to have you onboard!

**Comment by sJJdGG** [comment]
@sorousht Yep. count me in already.

**Comment by sorousht** [comment]
@sJJdGG Perfect! I've just added you :)

**Comment by Schabaani** [comment]
Hi dudes,
I am mobile developer and using react-native almost 1 year. 
I've started translating react from [crowdin](https://crowdin.com/project/react).

**Comment by tesseralis** [comment]
Hi all! You're all set. I added @masoud-bahrami from this issue: https://github.com/reactjs/reactjs.org-translation/pull/21

Your first assignment: How do I say "yes" and "no" for the translation website: isreacttranslatedyet.com

**Comment by masoud-bahrami** [comment]
@tesseralis  If you're sure about contributors, it's best to link Persian Translation to the site. 
For all PR by every contributors It is better to be reviewed by the rest of the members, and if approved, it should be accepted.
Having a dictionary for translated items can also be very helpful.

**Comment by tesseralis** [comment]
@sorousht @sJJdGG @zahrajoulaei @Schabaani @masoud-bahrami here's your repo! https://github.com/reactjs/fa.reactjs.org/issues/1

**Comment by SamaneYaghoobi** [comment]
@sorousht I enjoy translating react and just sending the link to beginners who don't know English well :)

**Comment by sorousht** [comment]
@SamaneYaghoobi Any contribution is welcome! We are in the begining of the way and it would be so much fun :)

**Comment by tesseralis** [comment]
Also, let me know if you need any help to get right-to-left text set up! The good thing about working on the repo itself is you can just change any settings to get it to work :)

**Comment by yasaminyaldaei** [comment]
Hi, I would be glad to contribute as well! I've started to learn JS and React about 6 months ago and I've used English resources so far. Also I have non-technical translation experience beforehand.

**Comment by sorousht** [comment]
Hi @yasaminyaldaei 

Great! We are preparing a contribution guideline document, but here is the workflow in brief:
 - Fork the [repo](https://github.com/reactjs/fa.reactjs.org)
 - Clone it on your local machine
 - Checkout to `fa` branch
 - Apply the change and commit
 - Push to [your-username]/fa.reactjs.org
 - Create a merge request from [your-username]:fa to [reactjs:fa](https://github.com/reactjs/fa.reactjs.org/tree/fa)
 - The merge request will be reviewed by at least 2 maintainers and, then will be merged :)

Please let us know if you have any question.

**Pull request merged**
