### PR TITLE
Added Kurdish language

### PR DESCRIPTION
**Pull request by Goran216**
I am a Kurdish software developer from Kurdistan region living in Dublin, Ireland. I don't have any translation experience but I have so much passion to grow this community. I have run a number of tech initiatives in Kurdistan during 2015 and 2016 which gave me a quite good number of connections across developer groups in the region. I will do my part to include as many contributors as possible while making sure that the translation is high-quality and up to react's standards. For now, I have included two of very good Kurdish developers I know who share the same passion as I have. We should be able to release the Kurdish language to production in a near future.

### CODE REVIEW

**Comment by tesseralis** [comment]
@Goran216 thanks for volunteering! @AlanHilal, @HeroMohammed could one of you respond verifying you want to be involved with the project? Once that's done I can get you started off.

**Comment by HeroMohammed** [comment]
@tesseralis Yes, I will be glad to contribute to this project.

**Comment by tesseralis** [comment]
Here you are! https://github.com/reactjs/ku.reactjs.org

**Comment by Goran216** [comment]
Thanks @tesseralis :)

**Pull request merged**
