### PR TITLE
Adds hindi translation JSON

### PR DESCRIPTION
**Pull request by arshadkazmi42**

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
Previous translation work
https://github.com/firstcontributions/first-contributions/blob/master/translations/README.hi.md

Reviewer for Hindi Language at [firstcontributions](firstcontributions)
https://github.com/firstcontributions/first-contributions/blob/master/.github/CONTRIBUTING.md#our-reviewers-sparkles

**Comment by tesseralis** [comment]
Hi! There's another pull request for hindi here: https://github.com/reactjs/reactjs.org-translation/pull/10

If you'd like to collaborate with @saranshkataria on it, leave a comment there with your experience with open source / translation!

**Comment by arshadkazmi42** [comment]
@tesseralis Thank you for the quick PR review 🙌

**Comment by tesseralis** [comment]
Here's your repo! https://github.com/reactjs/hi.reactjs.org/issues/1

**Pull request closed without merging**
