### PR TITLE
Add new maintainer to Tamil translation organization

### PR DESCRIPTION
**Pull request by majus28**
Add new maintainer to Tamil translation organization

### CODE REVIEW

**Comment by majus28** [comment]
@tesseralis Could you please look into this

**Comment by tesseralis** [comment]
Yup! It says you’re already a maintainer of Tamil

**Comment by pavinthan** [comment]
Ohh, sorry @tesseralis, I went wrong ? 🙇
but @sasureshkumar it isn't yet.

**Comment by tesseralis** [comment]
Sorry! Should be an invite now

**Comment by pavinthan** [comment]
@tesseralis Thank you so much 🙏

**Pull request merged**
