### PR TITLE
Add andrey-andreev as maintainer

### PR DESCRIPTION
**Pull request by andrey-andreev**
Hi, I would like to help with the Bulgarian translations.

### CODE REVIEW

**Comment by krasimir** [comment]
Welcome.

**Comment by jumpalottahigh** [comment]
@tesseralis Could you please help us add @andrey-andreev to the maintainers? He's still not in the team even though this PR was merged. Not sure if it's automatic or not.

**Comment by tesseralis** [comment]
sorry, was away from my computer. Should be done!

**Comment by andrey-andreev** [comment]
Thank you :)

**Comment by jumpalottahigh** [comment]
No worries, thanks a ton @tesseralis .

**Pull request merged**
