### PR TITLE
add Albanian language

### PR DESCRIPTION
**Pull request by asylejmani**
I'd like to contribute in translating the React docs in Albanian.

### CODE REVIEW

**Comment by tesseralis** [comment]
Hi, @asylejmani, @edonbajrami, could you talk a bit about what your open source or translation experiences are?

**Comment by EdinK1** [comment]
@tesseralis any updates on this? I'd be happy to take this on. I don't have any previous experience but I love react and I am a native Albanian speaker, so I'm confident that I can translate the docs.

**Comment by tesseralis** [comment]
@EdinK1 we're still waiting on the original two contributors to respond. If one of them responds I can start the translation with you and that person.

**Comment by asylejmani** [comment]
@tesseralis sorry I had missed your previous message. I don't have much open source contribution experience. Although I do work as a Frontender for 6+ years now and with the last 3 mainly in React. As far as translation goes, I've done simultaneous English - Albanian translations for a 6 physician conferences before I started coding.

**Comment by tesseralis** [comment]
@asylejmani thank you! @EdinK1 if you are okay with this arrangement I can start the repo with the three of you :)

**Comment by EdinK1** [comment]
@tesseralis sounds great! Thanks :)

**Comment by tesseralis** [comment]
@EdinK1 @asylejmani here's your repo: https://github.com/reactjs/sq.reactjs.org/issues/1

Sorry for the wait.

**Pull request merged**
