### PR TITLE
Add Ukrainian language

### PR DESCRIPTION
**Pull request by klymenkoo**
Hi,
I would like to work on Ukrainian translation of React.js docs. I have done a little bit of translation before (small iOS app), but I would be happy to contribute to React.
I also have an English blog on [Medium](https://medium.com/@volodymyrklymenko).

My friend @MargarytaChepiga also wants to contribute to this translation; she has done some [translations in Brave Browser](https://medium.com/margarytachepiga/release-0-2-part-1-39ca7be3a9e3).
I've also asked some people to join this project, so I might add some more maintainers later.

If anyone is interested to contribute, leave a comment 👇

### CODE REVIEW

**Comment by ApolllonDev** [comment]
@klymenkoo I would like to help!

**Comment by tesseralis** [comment]
@klymenkoo would you like to start now and add people later or would you like to wait a bit for people to respond?

**Comment by ithompson4** [comment]
Hello Volodymyr. I would like to help. Let me know what I can do.

**Comment by tesseralis** [comment]
@ithompson4 could you tell us a little more of your translation/open source experience?

**Comment by ithompson4** [comment]
I am a Seneca student. I am Ukrainian and can speak both Ukrainian and Russian. I am new to Open Source but have significant IT experience. Please feel free to look me up on linked in if you want more on my background linkedin.com/in/irynathompson. Thanks.

**Comment by klymenkoo** [comment]
> @klymenkoo would you like to start now and add people later or would you like to wait a bit for people to respond?

Yes, we can start now. Sounds good.

**Pull request merged**
