### PR TITLE
Added hebrew base config

### PR DESCRIPTION
**Pull request by bentlusty**
Initial commit for opening the Hebrew translation. I am not aware of any peers who are willing to contribute right now.

I don't have any open source translation projects but I did some English to Hebrew translation works before being a full time programmer.

### CODE REVIEW

**Comment by tesseralis** [comment]
Hi Ben! Thanks for volunteering. Let's leave this up to see if anyone else is interested in helping you!

**Comment by galnir** [comment]
I'm interested in helping you!

**Comment by tesseralis** [comment]
Awesome! @galnir could you tell us a bit of your translation or open source experience?

@bentlusty if you're okay with just the two of you, I can merge this in and you can get started!

**Comment by galnir** [comment]
I don't have experience in translating open source projects, but do have experience in translating articles from English to Hebrew, I hope that's enough

**Comment by bentlusty** [comment]
@tesseralis Yeah I think we're good. Let's get started!

**Comment by tesseralis** [comment]
Here's your issue! https://github.com/reactjs/he.reactjs.org/issues/1

Let me know if you need any help.

Also -- what's Hebrew for "yes" and "no"?

**Comment by bentlusty** [comment]
yes: כן
no: לא

**Pull request merged**
