### PR TITLE
updated

### PR DESCRIPTION
**Pull request by spielers**
added myself as a maintainer

### CODE REVIEW

**Comment by spielers** [comment]
hello @tesseralis I am currently working as a maintainer for gatsbyjs.org u can check my work and please help us to get started.

**Comment by tesseralis** [comment]
@visshaljagtap, @shrutikaponde could you approve this PR if you'd like to add @spielers as a maintainer to the Marathi translation?

**Comment by visshaljagtap** [comment]
HI @tesseralis , Currently we don't require any maintainer as there not much transalation requests for review. I have asked spielers to first translate the pages. He also started with one page translation. And in future if we require more maintainer, then for sure we will add.

**Comment by tesseralis** [comment]
Alright, as per @visshaljagtap's reply, I will close this PR for now.

**Pull request closed without merging**
