### PR TITLE
Add Belarusian translation

### PR DESCRIPTION
**Pull request by ptaberg**
Let's translate Reactjs docs into the Belarusian language! I have experience in translating services such as WhatsApp, Twitter, and Facebook (with the community) into Polish, Czech, Russian and Belarusian.

Also, I was an editor in Belarusian Wikipedia and I have translated many articles into the Belarusian language. I am a native speaker of Belarusian and Russian languages. I can and I can maintain the translation.

### CODE REVIEW

**Comment by AnatoliFront** [comment]
Yes, it's a good idea, let's do that.

**Comment by lukasbee1** [comment]
Hey, I'm also impressed to do that! I'll gratful for this opportunity

**Comment by tesseralis** [comment]
@anatolifront @lukasbee1 could you talk a little bit about your open source/translation experience?

**Comment by lukasbee1** [comment]
Hi, @tesseralis, I am one of the React.js Developers of the Belarusian community and I have experience in translating between Belarusian, Russian and English languages. I also translated more than 20 articles in Wikipedia into Belarusian and learned English from 8 years old. I am one of contributors on Belarusian translation in regional social networking website - vMotole.by (it's closed now).

**Comment by ptaberg** [comment]
I think I can help more with the Russian translation.

**Comment by tesseralis** [comment]
@lukasbee1 @AnatoliFront would you still like to help out with a Belariusian translation?

**Comment by tesseralis** [comment]
@lukasbee1 @AnatoliFront would you still like to help out with a Belariusian translation?

**Comment by lukasbee1** [comment]
@ptaberg was the main maintainter, I just supported him"

**Pull request closed without merging**
