### PR TITLE
Add Uzbek Language settings

### PR DESCRIPTION
**Pull request by turdiyev**
Initial commit for adding Uzbek language to react translation.

I have small translations experience with facebook and google-translate projects and my hobby project http://mana.uz (it's quotes collection in uzbek language. Some english quotes translated from english).

### CODE REVIEW

**Comment by tesseralis** [comment]
Thanks for contributing, @turdiyev ! Do you know any more people who would like to be maintainers?

**Comment by turdiyev** [comment]
@tesseralis hello. I will advertise this to Uzbek developers at the telegram group. I hope they join to us.

BTW, I already started translation at https://crowdin.com/translate/react/2858/en-uz

**Comment by umidbekkarimov** [comment]
@turdiyev ok, count me in :) I'm not good in writing, but I can help with organization and review.

**Comment by tesseralis** [comment]
@umidbekkarimov awesome! @turdiyev would you like to get started with the two of you or wait for more maintainers?

**Comment by umidbekkarimov** [comment]
@tesseralis let’s wait few days for other possible participants

**Comment by Shoyadbek** [comment]
Im ready

**Comment by tesseralis** [comment]
@Shoyadbek would you like to join? Could you tell us a little more about yourself?

**Comment by Shoyadbek** [comment]
@tesseralis Im from Tashkent, Uzbekistan. Uzbek my bative language. I use React / React Native for my local projects where automatization bussiness processes

**Comment by doniyor2109** [comment]
@turdiyev @umidbekkarimov @Shoyadbek Thanks for support

**Comment by jaloliddin-kuldoshev** [comment]
Hi everyone, I am also in.

**Comment by turdiyev** [comment]
@tesseralis, I think it's time to start now

**Comment by rustamwin** [comment]
I'm ready too

**Comment by tesseralis** [comment]
Okay! Merged with @turdiyev @umidbekkarimov @Shoyadbek as the initial maintainers. If you three want more, you should be able to add them!

**Comment by tesseralis** [comment]
Here's your repo! https://github.com/reactjs/uz.reactjs.org/issues/1

**Comment by sardoriy** [comment]
+++

**Comment by umidbekkarimov** [comment]
@sardoriy Welcome to https://github.com/reactjs/uz.reactjs.org/issues/1!

@tesseralis I think it's better to lock this thread for now

**Comment by aurshax** [comment]
> Hello @tesseralis. I’ll ask other Uzbek speaking developers I know. I hope they participate.
> 
> BTW, I already started translation at https://crowdin.com/translate/react/2858/en-uz

@turdiyev I am ready, too

**Comment by texnoman** [comment]
I'm ready too

**Comment by Curi0usPro** [comment]
> Thanks for contributing, @turdiyev ! Do you know any more people who would like to be maintainers?
Is this translation process going on?
If it is, i'm ready to contribute

**Pull request merged**
