### PR TITLE
 Add Armenian language

### PR DESCRIPTION
**Pull request by SurenAt93**
Hi, I would like to work on Armenian translation of React docs. Right now there are three maintainers; @tigrankeshishyan, @nikarm22 and me. I have also asked some people to join this project, so I might add some more maintainers later, but we would like to start it now. About experience; I have translated/written some technical documents, as an example you can check this one:
https://github.com/SurenAt93/Technical-Interview/blob/master/ti.eng.md
https://github.com/SurenAt93/Technical-Interview/blob/master/ti.arm.md

Guys also have an experience of writing/translating technical documents. And, we are using React more than three years as a main technology in daily work.

Thank you!

### CODE REVIEW

**Comment by tesseralis** [comment]
Awesome! I'm merging it in. Could you tell me how to say "yes" and "no" in Armenian?

**Comment by SurenAt93** [comment]
@tesseralis with pleasure :)
Yes - Այո
No - Ոչ

**Comment by tesseralis** [comment]
Your repo is created! You should have gotten an invite to join the reactjs org. Have fun translating!

**Comment by SurenAt93** [comment]
@tesseralis Thank you 🙂

**Comment by tigrankeshishyan** [comment]
Hey Dear Net.

Thank you for your fast response. We will do our best.

Regards,

Tigran

**Pull request merged**
