### PR TITLE
Adds Telugu translation support.

### PR DESCRIPTION
**Pull request by ashr81**
I would like to translate React related documentation into [Telugu](https://en.wikipedia.org/wiki/Telugu_language) to encourage local developers to use React.

I have 3 years of experience working on React.
And Telugu is my native language or mother tongue.
I will share this PR in Telugu tech communities.  To get in more support.

### CODE REVIEW

**Comment by tesseralis** [comment]
@ashr81 great! I'll leave this up if anyone wants to join :)

**Comment by KoushikKumar** [comment]
I would love to contribute for translation

**Comment by ashr81** [comment]
@tesseralis I got another maintainer added other than me. Can we add in the repository for language translation?

**Comment by tesseralis** [comment]
@ashr81 you got it!

**Pull request merged**
