### PR TITLE
Add Russian translation maintainers

### PR DESCRIPTION
**Pull request by lex111**
Hi everyone,

I wanted to take part in the translation documentation into Russian.

I have some experience of translation experience. I participated in translation of the [official PHP documentation](http://php.net/manual/ru/), [various books](https://leanpub.com/u/lex111) and [articles](https://medium.com/@lex111). As for React, this is a translation:
- [The Road to learn React book](https://leanpub.com/the-road-to-learn-react-russian)
- [Partial translation](https://ru.react.js.org/) of React documentation (repo - https://github.com/js-ru/react-ru)
- Two tutorial repositories, [react-from-zero](https://github.com/lex111/react-from-zero) and [react-developer-roadmap](https://github.com/lex111/react-developer-roadmap)

Therefore, I would like to have an official Russian translation of React documentation in near future.

As a maintainer, I indicated  tentatively @gaearon, because, as I understand it, he is interested in Russian translation (I hope this is still the case), as well as two people who have stated their desire to participate in the translation, @another-guy and @Heegiiny. I don't know them, but I expect that they will write in this PR to confirm their involvement.

### CODE REVIEW

**Comment by Heegiiny** [comment]
Yeah, I want to participate. My translation experience is not so wide, but I translated some technical guides and used react in my projects.

**Comment by gaearon** [comment]
I won’t have time to dedicate full effort to maintaining the translation myself but I’d like to be involved in early stages (to review first couple of pages and set the tone/principles for the doc).

**Comment by gaearon** [comment]
@tesseralis Leaving for you to merge

**Comment by another-guy** [comment]
@lex111 @tesseralis I do confirm I'm willing to help with translation.

Since this is going to be my first real open-source contribution, I can pick up any task where I'm helpful. I assume that an existing React repo member will define the body of work and the priorities.

**Comment by tesseralis** [comment]
@lex111 I've created a repo for you! You should have received an invite to join the react organization. Happy translating :)

**Comment by lex111** [comment]
@tesseralis thank you! :100:

**Pull request merged**
