### PR TITLE
Add taggon to the Korean translation maintainers

### PR DESCRIPTION
**Pull request by taggon**
Hello! I want to add myself to the Korean translation maintainers.

### CODE REVIEW

**Comment by taehwanno** [comment]
@tesseralis We all agreed through React Korea Slack :)

cc @simsim0709 @hg-pyun @gnujoow @b9words

**Comment by simsim0709** [comment]
@tesseralis I have tried to add @taggon, but I can't.

screen shot 2019-02-14 at 10 17 28 pm

**Comment by tesseralis** [comment]
You have to be an admin to do it. I'll do it soon.

**Comment by simsim0709** [comment]
Thanks!

**Comment by taggon** [comment]
Thanks @tesseralis! 🙇

**Pull request merged**
