### PR TITLE
Add Urdu translation

### PR DESCRIPTION
**Pull request by jabranr**
Adding Urdu support for translation as I believe it would benefit a huge community worldwide. I have experience of translation with few products of Google and Facebook platform itself. I have been a product advocate for Google Map Maker for several years and maintained few online communities during that period. At the moment, it is only myself listed as a maintainer here but I am hoping more people join the effort once I ask the community.

### CODE REVIEW

**Comment by tesseralis** [comment]
Hi @jabranr that's awesome! Let's keep this up so that other people can find it.

**Comment by armujahid** [comment]
@jabranr you can add me as maintainer. I don't have English to Urdu translation experience but I think I can handle most of the maintainer responsibilities.

1. I am [Professional React Nanodegree](https://graduation.udacity.com/confirm/RCSRX37S) graduate from Udacity
2. Urdu is my first language.

**Comment by jabranr** [comment]
@armujahid Awesome! I have updated the maintainer list to include you.

**Comment by tesseralis** [comment]
Here you go! https:github.com/reactjs/ur.reactjs.org/issues/1

**Comment by abdullah1908** [comment]
Hey @jabranr,

I am the WP expert, Open Source Contributor & translation editor @WordPress for Urdu. I would love to maintain strings for react as well.
Here is my WP.org Profile: https://profiles.wordpress.org/abdullahramzan

Thank you,

**Comment by armujahid** [comment]
@abdullah1908 you can claim any of the core pages mentioned [here](https://github.com/reactjs/ur.reactjs.org/issues/1). Let us know which page you want to translate. We will then update that issue.

**Comment by abdullah1908** [comment]
Thanks for your response @armujahid  :+1: 

You can assign any of the page, would love to suggest Urdu strings :)

**Pull request merged**
