### PR TITLE
feat(langs): added language config for haitian creole (ht)

### PR DESCRIPTION
**Pull request by darkfadr**
This PR is the first step in starting the translation effort of the reactjs.org documentation from English into Haitian Creole.

@jgb-solutions @didierganthier @mama00 @leregi @PrinceLouis could you please confirm your involvement in this project by responding in the comments below. 

I would like to publicly express my appreciation for your willingness to help with this cause. 
👏👏  😃

### CODE REVIEW

**Comment by mama00** [comment]
I would like to publicly express my appreciation for your willingness to help with this cause.
👏👏 😃

**Comment by darkfadr** [comment]
@mama00 Does this mean that you are in? 😄

**Comment by mama00** [comment]
Absolutly


Le sam. 26 oct. 2019 à 18:25, Ashley Narcisse <notifications@github.com> a
écrit :

**Comment by jgb-solutions** [comment]
Hey there! I'm in 100%

**Comment by didierganthier** [comment]
I am ready to contribute to this project  :)

**Comment by tesseralis** [comment]
@darkfadr you should be all set up! https://github.com/reactjs/ht.reactjs.org

Happy translating! And let me know if you have any questions.

**Pull request merged**
