### PR TITLE
Add Macedonian language

### PR DESCRIPTION
**Pull request by krisfremen**
Hey there,

I would like to translate reactjs.org in Macedonian.

Cheers!

### CODE REVIEW

**Comment by krisfremen** [comment]
hi there @carburo, 

I noticed @tesseralis hasn't been active in a while.
Is it possible for you to approve and merge this PR?

Thanks!

**Comment by carburo** [comment]
Hi, @krisfremen! Sorry, I'm a maintainer of the Spanish translation site, so I shouldn't approve anything outside that scope. Someone from the React Core Team should approve this PR.

**Comment by krisfremen** [comment]
@tesseralis hi there, reaching out to see if this can get approved and merged in. Thanks!

**Comment by gaearon** [comment]
Hi folks, sorry for no response.

We've been working on new React docs, and so translations of the old site were deprioritized.
In the meantime, it looks like our GitHub permissions sync may have broke.

Now that we've rolled out the new site and reset the repositories for new translations, I'm going to close all old pull requests including this one so that we can start from a clean slate. If you'd like to still make the same change, please open a new PR.

Thanks, and sorry for the churn.

**Pull request closed without merging**
