### PR TITLE
Added Marathi language

### PR DESCRIPTION
**Pull request by pnutmath**
I would like to contribute to React community by translating reactjs.org in Marathi language.

### CODE REVIEW

**Comment by tesseralis** [comment]
Hi @pnutdev, thanks for contributing! Could you and @zilurrane tell us a little more about your language or open source background?

**Comment by pnutdev** [comment]
> Hi @pnutdev, thanks for contributing! Could you and @zilurrane tell us a little more about your language or open source background?

I do not have any experience in translation before but would love to initiate translation process for Marathi My mother tongue is Marathi and i am very well know about it.

**Comment by tesseralis** [comment]
@pnutdev thanks for the reply! @zilurrane could you reply as well to make sure both maintainers are bought into the project?

**Comment by mahadevpunekar** [comment]
hey nice library ...can start consuming ....
and I also wanted in angular ..

**Comment by DrHrishi** [comment]
@pnutmath I created a pull request for Marathi, please add me as maintainer for this, so that I can close that pull request. I have experience in translation but because of our database is not fully setup , we haven't release that. 
Thank You,
Hrishikesh

**Comment by DrHrishi** [comment]
Thanks,
@pnutmath,
 @tesseralis , Please review so that we can start contributing , Thanks.

**Comment by gaearon** [comment]
Hi folks, sorry for no response.

We've been working on new React docs, and so translations of the old site were deprioritized.
In the meantime, it looks like our GitHub permissions sync may have broke.

Now that we've rolled out the new site and reset the repositories for new translations, I'm going to close all old pull requests including this one so that we can start from a clean slate. If you'd like to still make the same change, please open a new PR.

Thanks, and sorry for the churn.

**Pull request closed without merging**
