### PR TITLE
Add Bengali Language

### PR DESCRIPTION
**Pull request by nutboltu**
Hello,

I would love to contribute on translating to `Bengali` language.

- Maintainer of Bengali Language support in [date-fns](https://github.com/date-fns/date-fns).
- Maintainer of Bengali Language support in [system-design-primer](https://github.com/donnemartin/system-design-primer) - WIP

### CODE REVIEW

**Comment by tesseralis** [comment]
@nutboltu Thanks for volunteering! Let's wait for more maintainers, then I'll get you started up!

**Comment by tesseralis** [comment]
@zahidulmcc could you tell us more about your translation or open source background?

**Comment by nutboltu** [comment]
@tesseralis  I added @zahidulmcc as a maintainer.

https://github.com/zahidulmcc

- Native Bengali speaker.
- Experienced on React
- Open source contributer

**Comment by zahidulmcc** [comment]
As @nutboltu mentioned. I am a experienced React Developer and Bengali is my mother tongue.
We are very much interested to contribute and maintain Bengali Language support. Thanks in advance.

**Comment by nutboltu** [comment]
@tesseralis I tweeted for more maintainers.
https://twitter.com/nutboltu/status/1095170733620244480

**Comment by tesseralis** [comment]
Okay! Now you both have commented I'll get you started. You can add more maintainers later by editing this file :)

**Comment by tesseralis** [comment]
Here you go!

https://github.com/reactjs/bn.reactjs.org/issues/1

Please use this issue to keep track of your progress.

**Pull request merged**
