### PR TITLE
For Rich Punjabi Language - Adding myself as a maintainer

### PR DESCRIPTION
**Pull request by sarbjithanjra**
I like to translate React documents into Punjabi language so millions of Punjabi language speaker around the world can take benefits of rich  React library to build multilingual Web User Interface and more ...

### CODE REVIEW

**Comment by tesseralis** [comment]
Hi @sarbjithanjra! Thanks for volunteering. We'll keep this PR up and wait for more maintainers.

**Comment by sarbjithanjra** [comment]
Thanks @tesseralis  for quick response.  I will wait, when I can start translation :)

**Comment by ranjeetsinghmk** [comment]
@sarbjithanjra Veerji I would like to contribute.

**Review by ranjeetsinghmk — APPROVED** [review]

**Comment by ranjeetsinghmk** [comment]
Hi @tesseralis I would like to contribute to the same.

**Comment by gaearon** [comment]
Hi folks, sorry for no response.

We've been working on new React docs, and so translations of the old site were deprioritized.
In the meantime, it looks like our GitHub permissions sync may have broke.

Now that we've rolled out the new site and reset the repositories for new translations, I'm going to close all old pull requests including this one so that we can start from a clean slate. If you'd like to still make the same change, please open a new PR.

Thanks, and sorry for the churn.

**Pull request closed without merging**
