### PR TITLE
Add Belarusian language support

### PR DESCRIPTION
**Pull request by wiedymi**
Hi! I would like to translate reactjs.org to belarusian language. This is an official language in Belarus.

### CODE REVIEW

**Comment by wiedymi** [comment]
@tesseralis please, review it.

**Review by SmolinPavel — APPROVED** [review]

**Comment by SmolinPavel** [comment]
@tesseralis could you please review this PR?

**Comment by zubialevich** [comment]
Hi! Can you add me to the maintainers list?

**Comment by zubialevich** [comment]
Is it possible to add new locales for translation? Seems bot have some problems #196

**Comment by SmolinPavel** [comment]
@wiedymi sorry, I don't have permissions to merge. I was just trying to speed up the process of this PR to be merged.

**Comment by gaearon** [comment]
Hi folks, sorry for no response.

We've been working on new React docs, and so translations of the old site were deprioritized.
In the meantime, it looks like our GitHub permissions sync may have broke.

Now that we've rolled out the new site and reset the repositories for new translations, I'm going to close all old pull requests including this one so that we can start from a clean slate. If you'd like to still make the same change, please open a new PR.

Thanks, and sorry for the churn.

**Pull request closed without merging**
