### PR TITLE
Add Portuguese (Portugal) language

### PR DESCRIPTION
**Pull request by telmogoncalves**
Initial commit and proposal for Portuguese (Portugal) translations.

We'll keep this here for now until we have more maintainers and it makes sense to merge.

### CODE REVIEW

**Comment by jbarradas** [comment]
I'm in! Let me know if this goes through ;)

**Comment by tesseralis** [comment]
@telmogoncalves @jbarradas could you talk a little bit about your translation/open source experience?

**Comment by telmogoncalves** [comment]
> @telmogoncalves @jbarradas could you talk a little bit about your translation/open source experience?

Don't have much experience, mainly from own projects. Guess I need to start somewhere, if that's OK.

**Comment by jbarradas** [comment]
@tesseralis, no translation experience, but proud of my non-literal English to Portuguese translation.

**Comment by fjoshuajr** [comment]
I'm whiling to help too.
I have a bit of experience translating a few legacy systems documentation at the company I work for. And I also already contribute to the pt-BR repo.

**Comment by jbarradas** [comment]
Correction: "willing" instead of "whiling"

**Comment by fjoshuajr** [comment]
> Correction: "willing" instead of "whiling".
> 
> Also, PT-br is different from PT in many ways. I wouldn't advise to be translating both at the same time.

Right. The thing is, I originally wanted to contribute to the pt-pt but it didn't exist at the time only the pt-br, so I went that way. And you can see the comment that I made [here](https://github.com/reactjs/pt-BR.reactjs.org/issues/1#issuecomment-461790088).

**Comment by telmogoncalves** [comment]
As long as you are not contributing to both at the same time, I guess we're good.

We still need to get more maintainers anyway.

**Comment by tesseralis** [comment]
@telmogoncalves I think you can get started with the three of you if you'd like!

**Comment by telmogoncalves** [comment]
> @telmogoncalves I think you can get started with the three of you if you'd like!

Absolutely. I'll also raise a PR in the `pt-BR` to remove myself from the maintainers.

This PR needs to be merged so we can move on right?

**Comment by tesseralis** [comment]
Yup! Your repo is being created now!

**Pull request merged**
