### PR TITLE
Add Polish language

### PR DESCRIPTION
**Pull request by cvqprs**

### CODE REVIEW

**Comment by tesseralis** [comment]
Hi! If you'd like to join the current polish language implementation, please ask the current maintainers, @jakubdrozdek, @bartlomiejzuber, and @TeoTN to add you as a maintainer!

**Comment by tesseralis** [comment]
You can see the current translation effort here: https://github.com/reactjs/pl.reactjs.org/issues/1

**Comment by jakubdrozdek** [comment]
@tesseralis I'm unable to add @cvqprs as a Maintainer, because he/she is not a member of the Polish reactjs.org team. I can only add people as regular members, e.g. with 'Write' access only. Is that what you meant?

**Comment by tesseralis** [comment]
@jakubdrozdek I added them! In the future, you need to go to the Polish team -> Members -> Add a team member, and it will invite the to join the reactjs.org organization.

**Comment by jakubdrozdek** [comment]
Maybe I'm doing something totally wrong, but... I can't invite people to the team unless they are members of the organization:
image

**Comment by tesseralis** [comment]
Huh... I'll look into it

**Comment by tesseralis** [comment]
Oh I see, it seems only owners of reactjs.org can invite people. I'll figure out some way to make this process easier. :)

**Comment by jakubdrozdek** [comment]
Great! I wouldn't want to bother you every time a new member appears :-) I think other translation teams think the same.

**Comment by tesseralis** [comment]
Haha, I'll probably automate it just like I automated creating all the repos :)

**Pull request closed without merging**
