### PR TITLE
Adding Burmese to translations

### PR DESCRIPTION
**Pull request by devayarhlaine**

### CODE REVIEW

**Comment by tesseralis** [comment]
Thanks for volunteering, @devayarhlaine! We'll keep this open to see if anyone else would like to join.

**Comment by devayarhlaine** [comment]
Thanks @tesseralis.I will also try out more maintainers.

**Comment by SArkar-Htet** [comment]
@devayarhlaine , I wanna join with you.

**Comment by devayarhlaine** [comment]
> @devayarhlaine , I wanna join with you.

Thanks Bro, I already added you to maintainer list.

**Comment by devayarhlaine** [comment]
Hello @tesseralis , we got total of 4 maintainers to translate.

**Comment by nayyaung9** [comment]
@devayarhlaine I will join bro, I would love to do translation process for Burma (Myanmar). My mother tongue is Burma and I know very well about it.

**Comment by devayarhlaine** [comment]
> @devayarhlaine I will join bro, I would love to do translation process for Burma (Myanmar). My mother tongue is Burma and I know very well about it.

yes, sure bro.

**Comment by devayarhlaine** [comment]
For later PRs, we will go through our organization,  https://github.com/react-js-myanmar

**Comment by tesseralis** [comment]
Hi everyone! I've created the repo at https://github.com/reactjs/my.reactjs.org. Happy translating :)

**Comment by devayarhlaine** [comment]
Hello @tesseralis , thanks for allowed us to translate.

**Comment by devayarhlaine** [comment]
Hello @tesseralis , we will fork https://github.com/reactjs/my.reactjs.org repo,it is ok, then how can we inform you which maintainer is doing which page?

**Comment by tesseralis** [comment]
You can use this issue to track progress: https://github.com/reactjs/my.reactjs.org/issues/1

It should list the pages you should tackle first.

**Comment by devayarhlaine** [comment]
yes, thank you for guiding us. We will comment who will translate which page in this issue reactjs/my.reactjs.org#1 .

**Pull request merged**
