### PR TITLE
Added Romanian lang

### PR DESCRIPTION
**Pull request by RaulTsc**
Added Romanian language.

I don't have so much experience doing translations but I do a lot of writing in my free time, both En and Ro.
Would definitely like it if someone more experienced will join. Keeping this PR open until then.

### CODE REVIEW

**Comment by RaulTsc** [comment]
Will wait a few days in case someone wants to join.

**Comment by nikiciv** [comment]
Will help @RaulTsc with Romanian language.

**Comment by tesseralis** [comment]
@nikiciv could you say a little bit about your experience?

**Comment by nikiciv** [comment]
@tesseralis I'm a Front End dev, I don't have too much experience with open source, but I am willing to make.Related to translating experience: I write a lot in En & Ro in my free time too, so this should not be a concern.

**Comment by tesseralis** [comment]
@RaulTsc Okay seems that we have two maintainers. @RaulTsc say the word and I'll start up your repo for you :)

**Comment by RaulTsc** [comment]
let's wait a few more days in case someone more experienced wants to join

**Comment by tesseralis** [comment]
@RaulTsc it's been a few days, so I'll merge your repo in for now and we can add more people later!

**Comment by tesseralis** [comment]
@RaulTsc @nikiciv here's your repo!

https://github.com/reactjs/ro.reactjs.org/issues/1

Please use this issue to track your progress.

**Comment by RaulTsc** [comment]
thanks @tesseralis 

sure, I would really love for more people to join!

**Pull request merged**
