### PR TITLE
Adding Arabic to translations

### PR DESCRIPTION
**Pull request by 22mahmoud**
I don't have much experience in the translation field, But I wanna to be a maintainer/contributor in that project.
So I'm gonna share this pull-request in  Arabic tech. communities (Facebook, Twitter).

### CODE REVIEW

**Comment by tesseralis** [comment]
Thanks! Let's wait until some more people join in.

I also saw this on twitter: https://twitter.com/aalagha/status/1094295425153187841

It seems like there's previous work done? It may be worth reaching out to these folks to see if they would like to contribute.

**Comment by SaifAsad** [comment]
@22mahmoud thank you for creating this issue, I will be glad to contribute to translate this awesome library's docs to Arabic - I don't have previous translation experience - but I am a native Arabic speaker.

**Comment by tesseralis** [comment]
@22mahmoud if you're alright with just the two of you, say the word and I'll get you started up :)

**Comment by Emmanuel-Melon** [comment]
I'd also like to contribute to this, where do I get started?

**Comment by tesseralis** [comment]
@Emmanuel-Melon if you would like to be a maintainer, tell us a little about your translation or open source experience. If you would just like to contribute translations, once this PR is merged in I'll link you to more instructions!

**Comment by Emmanuel-Melon** [comment]
- **Translation experience**: I am bilingual and 80% of my education has been in Arabic.
- **Open source experience**: I haven't made any contributions but I'd like begin contributing.

**Comment by aalagha** [comment]
We already have an Arabic translation of React and React Native here:

https://wiki.hsoub.com/React
https://wiki.hsoub.com/ReactNative

Feel free to use it.

**Comment by 22mahmoud** [comment]
@tesseralis  I'm ready to start and @aalagha  wiki It'll be our base to start with

**Comment by iRayan7** [comment]
@aalagha Thanks Abdulmuhaimen. That will speed things up!

I'd like to be a maintainer as well. I'm a native Arabic speaker.

**Comment by tesseralis** [comment]
Here you go! https://github.com/reactjs/ar.reactjs.org/issues/1

**Comment by asantarissy** [comment]
@tesseralis I'd love to be part of this, I'm a native Arabic speaker and I have a good expreciance in RTL interfaces and translations. 😄

**Comment by tesseralis** [comment]
@asantarissy Just edit the file to add your name and ask the current maintainers if you can join!

**Comment by asantarissy** [comment]
Thanks @tesseralis, just to make sure, do you mean the ar.json file?

@22mahmoud, @SaifAsad, @Emmanuel-Melon and @iRayan7 I'd love to be part of this and help you guys finish it بسرعة 😊

**Comment by tesseralis** [comment]
Yup!

**Comment by tesseralis** [comment]
Just submit a PR adding your name.

**Comment by asantarissy** [comment]
@tesseralis done, thanks again.

**Comment by iRayan7** [comment]
@asantarissy For sure! أهلًا وسهلًا

**Pull request merged**
