### PR TITLE
Adding Cambodian language to translations

### PR DESCRIPTION
**Pull request by Bunlong**
@bunlong @lengsovandara We don't have much experience in the translation field, But we wanna to be maintainers/contributors in this project with Cambodian (Khmer) language translations.

### CODE REVIEW

**Comment by tesseralis** [comment]
@Bunlong thanks for volunteering! @lengsovandara could you post here confirming that you'd like to be involved in this project?

**Comment by lengsovandara** [comment]
@Bunlong and I want to be maintainers/contributors in this project with our Khmer Language.

**Comment by tesseralis** [comment]
Here you go! https://github.com/reactjs/km.reactjs.org/issues/1

**Comment by Bunlong** [comment]
@tesseralis Yes, We got it. Thank you!

**Comment by lengsovandara** [comment]
@tesseralis Thank you

**Pull request merged**
