### PR TITLE
Adding german to translations

### PR DESCRIPTION
**Pull request by ChrisB9**
I'd like to contribute by starting to add german to the list.
I also am searching for anyone willing to help translating.

For the experience part:
I translated some stuff already for couple open-source projects such as [https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-](Google Play Music Desktop Player) and [https://github.com/iluminar/goodwork](GoodWork).

### CODE REVIEW

**Comment by tesseralis** [comment]
@ChrisB9 Thanks for volunteering! Let's wait for other contributors to join then I'll merge this!

**Comment by ph1p** [comment]
Hi! I'm also interested (: ... Previously I've worked on german translations of rocket.chat and buttercup.

**Comment by tesseralis** [comment]
@ChrisB9 say the word and I'll merge the repo!

**Comment by miku86** [comment]
Hey folks,
I also would love to volunteer!
I've worked on some translations at university.

**Comment by ChrisB9** [comment]
@tesseralis alright, then let's go for it ✌️

**Comment by tesseralis** [comment]
Here's your repo! https://github.com/reactjs/de.reactjs.org/issues/1

**Pull request merged**
