### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by deblasis**
Hi there, I am happy to contribute to this and of course, more maintainers are very welcome!

In terms of experience, I used to do English to Italian translations for the Notebook reviews website [Notebookcheck.com](https://www.notebookcheck.com/)  => [Notebookcheck.it](https://www.notebookcheck.it)

### CODE REVIEW

**Comment by tesseralis** [comment]
Hi @deblasis ! Thanks for volunteering! Let's wait for other maintainers to show up then we'll get you started!

**Comment by LucaBlackDragon** [comment]
Hi, I'd love to join too if help is needed. I've got no previous experiences apart from having contributed to the Visual Studio Code and Azure Data Studio community localisation projects.

**Comment by tesseralis** [comment]
Perfect! @deblasis let me know if you're alright with just two of you to start and I'll merge this repo in!

**Comment by deblasis** [comment]
@tesseralis I am happy to start just the two of us and let's see how that goes.

Welcome @LucaBlackDragon! Or I should say... `Ciao!` 😄

**Comment by LucaBlackDragon** [comment]
@deblasis hi/ciao! :D

**Comment by tesseralis** [comment]
Let's get you two started!

**Comment by tesseralis** [comment]
Here's your repo! https://github.com/reactjs/it.reactjs.org/issues/1

Use this issue to track your progress. Happy translatiing!

**Pull request merged**
